import '@styles/global.css';

import { Raleway } from 'next/font/google';

import { Providers } from './provider';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Next14 TypeScript Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={raleway.className}>
        <Providers>
          <div className="mx-auto max-w-xl shadow-md">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
