import '@styles/global.css';

import { Providers } from './provider';

export const metadata = {
  title: 'Next14 TypeScript Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <div className="mx-auto max-w-xl leading-tight shadow-md">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
